---
Name: ecommerce_dashboard
After: 'framework/*','cms/*','dashboard/*', 'ecommerce/*'
---
LeftAndMain:
  extra_requirements_css:
   - 'ecommerce_dashboard/css/ecommercedashboard.css'

AdminRootController:
  default_panel: 'CMSMain'
---
Only:
  moduleexists: 'grouped-cms-menu'
---
LeftAndMain:
  menu_groups:
    Shop:
      - EcommerceDashboard
